# Generated by Django 4.2.3 on 2024-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Name')),
                ('full_text', models.TextField(verbose_name='Project')),
                ('github_link', models.CharField(max_length=50, verbose_name='Github link')),
                ('anons', models.CharField(max_length=50, verbose_name='Anons')),
            ],
        ),
    ]
