# Generated by Django 5.1.1 on 2025-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='video',
        ),
        migrations.AddField(
            model_name='projects',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
